// Comprehensive global logistics database for complete worldwide coverage
export const comprehensiveLocations = [
  // Major Global Ports - Africa
  { name: "Port de Durban, Afrique du Sud", coordinates: [31.0218, -29.8587], type: "port", aliases: ["durban port", "port durban", "durban"] },
  { name: "Port du Cap, Afrique du Sud", coordinates: [18.4265, -33.9058], type: "port", aliases: ["cape town port", "port cape town", "port du cap"] },
  { name: "Port de Casablanca, Maroc", coordinates: [-7.6164, 33.6022], type: "port", aliases: ["casablanca port", "port casablanca"] },
  { name: "Port de Tanger Med, Maroc", coordinates: [-5.4972, 35.9167], type: "port", aliases: ["tanger med", "tangier med", "port tanger"] },
  { name: "Port de Lagos, Nigéria", coordinates: [3.3792, 6.5244], type: "port", aliases: ["lagos port", "port lagos", "apapa port"] },
  { name: "Port de Mombasa, Kenya", coordinates: [39.6682, -4.0435], type: "port", aliases: ["mombasa port", "port mombasa"] },
  { name: "Port de Dakar, Sénégal", coordinates: [-17.4441, 14.7167], type: "port", aliases: ["dakar port", "port dakar"] },
  { name: "Port d'Abidjan, Côte d'Ivoire", coordinates: [-4.0435, 5.3599], type: "port", aliases: ["abidjan port", "port abidjan"] },
  { name: "Port de Djibouti", coordinates: [43.1456, 11.5883], type: "port", aliases: ["djibouti port", "port djibouti"] },
  { name: "Port Saïd, Égypte", coordinates: [32.3019, 31.2653], type: "port", aliases: ["port said", "suez canal", "port suez"] },
  { name: "Port d'Alexandrie, Égypte", coordinates: [29.8889, 31.2001], type: "port", aliases: ["alexandria port", "port alexandria"] },
  { name: "Port de Luanda, Angola", coordinates: [13.2302, -8.8390], type: "port", aliases: ["luanda port", "port luanda"] },
  { name: "Port de Maputo, Mozambique", coordinates: [32.5832, -25.9653], type: "port", aliases: ["maputo port", "port maputo"] },
  { name: "Port de Lomé, Togo", coordinates: [1.2255, 6.1319], type: "port", aliases: ["lome port", "port lome"] },
  { name: "Port de Cotonou, Bénin", coordinates: [2.4418, 6.3703], type: "port", aliases: ["cotonou port", "port cotonou"] },
  { name: "Port de Tema, Ghana", coordinates: [-0.0167, 5.6667], type: "port", aliases: ["tema port", "port tema"] },
  { name: "Port de Takoradi, Ghana", coordinates: [-1.7540, 4.8845], type: "port", aliases: ["takoradi port", "port takoradi"] },
  { name: "Port de Freetown, Sierra Leone", coordinates: [-13.2317, 8.4657], type: "port", aliases: ["freetown port", "port freetown"] },
  { name: "Port de Conakry, Guinée", coordinates: [-13.6773, 9.5380], type: "port", aliases: ["conakry port", "port conakry"] },
  { name: "Port de Nouakchott, Mauritanie", coordinates: [-15.9785, 18.0858], type: "port", aliases: ["nouakchott port", "port nouakchott"] },

  // Major Global Ports - Europe
  { name: "Port de Rotterdam, Pays-Bas", coordinates: [4.1427, 51.9244], type: "port", aliases: ["rotterdam port", "port rotterdam", "europoort"] },
  { name: "Port d'Anvers, Belgique", coordinates: [4.4025, 51.2194], type: "port", aliases: ["antwerp port", "port antwerp", "anvers"] },
  { name: "Port de Hamburg, Allemagne", coordinates: [9.9937, 53.5511], type: "port", aliases: ["hamburg port", "port hamburg"] },
  { name: "Port du Havre, France", coordinates: [0.1070, 49.4944], type: "port", aliases: ["le havre port", "port le havre", "havre"] },
  { name: "Port de Marseille, France", coordinates: [5.3698, 43.2965], type: "port", aliases: ["marseille port", "port marseille"] },
  { name: "Port de Gênes, Italie", coordinates: [8.9463, 44.4056], type: "port", aliases: ["genoa port", "port genoa", "genova"] },
  { name: "Port de Barcelone, Espagne", coordinates: [2.1734, 41.3851], type: "port", aliases: ["barcelona port", "port barcelona"] },
  { name: "Port de Valencia, Espagne", coordinates: [-0.3762, 39.4699], type: "port", aliases: ["valencia port", "port valencia"] },
  { name: "Port de Lisbonne, Portugal", coordinates: [-9.1393, 38.7223], type: "port", aliases: ["lisbon port", "port lisbon"] },
  { name: "Port de Felixstowe, Royaume-Uni", coordinates: [1.3511, 51.9542], type: "port", aliases: ["felixstowe port", "port felixstowe"] },
  { name: "Port de Southampton, Royaume-Uni", coordinates: [-1.4044, 50.9097], type: "port", aliases: ["southampton port", "port southampton"] },
  { name: "Port de Göteborg, Suède", coordinates: [11.9746, 57.7089], type: "port", aliases: ["gothenburg port", "port gothenburg"] },
  { name: "Port d'Oslo, Norvège", coordinates: [10.7522, 59.9139], type: "port", aliases: ["oslo port", "port oslo"] },
  { name: "Port de Copenhague, Danemark", coordinates: [12.5683, 55.6761], type: "port", aliases: ["copenhagen port", "port copenhagen"] },
  { name: "Port d'Helsinki, Finlande", coordinates: [24.9384, 60.1699], type: "port", aliases: ["helsinki port", "port helsinki"] },
  { name: "Port de Saint-Pétersbourg, Russie", coordinates: [30.3351, 59.9311], type: "port", aliases: ["st petersburg port", "port st petersburg"] },

  // Major Global Ports - Asia
  { name: "Port de Shanghai, Chine", coordinates: [121.5000, 31.2000], type: "port", aliases: ["shanghai port", "port shanghai", "yangshan"] },
  { name: "Port de Singapour", coordinates: [103.8198, 1.3521], type: "port", aliases: ["singapore port", "port singapore", "psa"] },
  { name: "Port de Hong Kong", coordinates: [114.1694, 22.3193], type: "port", aliases: ["hong kong port", "port hong kong"] },
  { name: "Port de Busan, Corée du Sud", coordinates: [129.0756, 35.1796], type: "port", aliases: ["busan port", "port busan", "pusan"] },
  { name: "Port de Tokyo, Japon", coordinates: [139.7594, 35.6581], type: "port", aliases: ["tokyo port", "port tokyo"] },
  { name: "Port de Yokohama, Japon", coordinates: [139.6380, 35.4437], type: "port", aliases: ["yokohama port", "port yokohama"] },
  { name: "Port de Kobe, Japon", coordinates: [135.1955, 34.6901], type: "port", aliases: ["kobe port", "port kobe"] },
  { name: "Port de Shenzhen, Chine", coordinates: [114.0579, 22.5431], type: "port", aliases: ["shenzhen port", "port shenzhen"] },
  { name: "Port de Ningbo, Chine", coordinates: [121.5440, 29.8683], type: "port", aliases: ["ningbo port", "port ningbo"] },
  { name: "Port de Tianjin, Chine", coordinates: [117.1889, 39.1422], type: "port", aliases: ["tianjin port", "port tianjin"] },
  { name: "Port de Qingdao, Chine", coordinates: [120.3826, 36.0986], type: "port", aliases: ["qingdao port", "port qingdao"] },
  { name: "Port de Mumbai, Inde", coordinates: [72.8777, 19.0760], type: "port", aliases: ["mumbai port", "port mumbai", "bombay port"] },
  { name: "Port de Chennai, Inde", coordinates: [80.2707, 13.0827], type: "port", aliases: ["chennai port", "port chennai", "madras port"] },
  { name: "Port de Jawaharlal Nehru, Inde", coordinates: [72.9629, 18.9388], type: "port", aliases: ["jnpt", "nhava sheva", "port mumbai"] },
  { name: "Port de Colombo, Sri Lanka", coordinates: [79.8612, 6.9271], type: "port", aliases: ["colombo port", "port colombo"] },
  { name: "Port de Chittagong, Bangladesh", coordinates: [91.8311, 22.3569], type: "port", aliases: ["chittagong port", "port chittagong"] },
  { name: "Port de Karachi, Pakistan", coordinates: [67.0011, 24.8607], type: "port", aliases: ["karachi port", "port karachi"] },
  { name: "Port de Bangkok, Thaïlande", coordinates: [100.5018, 13.7563], type: "port", aliases: ["bangkok port", "port bangkok", "laem chabang"] },
  { name: "Port de Ho Chi Minh, Vietnam", coordinates: [106.6297, 10.8231], type: "port", aliases: ["ho chi minh port", "saigon port", "port saigon"] },
  { name: "Port de Manille, Philippines", coordinates: [120.9842, 14.5995], type: "port", aliases: ["manila port", "port manila"] },
  { name: "Port de Jakarta, Indonésie", coordinates: [106.8451, -6.2088], type: "port", aliases: ["jakarta port", "port jakarta", "tanjung priok"] },

  // Major Global Ports - Middle East
  { name: "Port de Dubaï, Émirats Arabes Unis", coordinates: [55.2708, 25.2048], type: "port", aliases: ["dubai port", "port dubai", "jebel ali"] },
  { name: "Port d'Abu Dhabi, Émirats Arabes Unis", coordinates: [54.3773, 24.4539], type: "port", aliases: ["abu dhabi port", "port abu dhabi"] },
  { name: "Port de Doha, Qatar", coordinates: [51.5310, 25.2854], type: "port", aliases: ["doha port", "port doha"] },
  { name: "Port du Koweït", coordinates: [47.9774, 29.3697], type: "port", aliases: ["kuwait port", "port kuwait"] },
  { name: "Port de Bahreïn", coordinates: [50.5577, 26.0667], type: "port", aliases: ["bahrain port", "port bahrain"] },
  { name: "Port de Mascate, Oman", coordinates: [58.4059, 23.5880], type: "port", aliases: ["muscat port", "port muscat"] },
  { name: "Port de Bandar Abbas, Iran", coordinates: [56.2808, 27.1865], type: "port", aliases: ["bandar abbas port", "port bandar abbas"] },

  // Major Global Ports - Americas
  { name: "Port de Los Angeles, États-Unis", coordinates: [-118.2437, 33.7405], type: "port", aliases: ["la port", "los angeles port", "port los angeles"] },
  { name: "Port de Long Beach, États-Unis", coordinates: [-118.2437, 33.7701], type: "port", aliases: ["long beach port", "port long beach"] },
  { name: "Port de New York, États-Unis", coordinates: [-74.0445, 40.6892], type: "port", aliases: ["new york port", "port new york", "ny nj port"] },
  { name: "Port de Savannah, États-Unis", coordinates: [-81.0912, 32.0835], type: "port", aliases: ["savannah port", "port savannah"] },
  { name: "Port de Charleston, États-Unis", coordinates: [-79.9311, 32.7765], type: "port", aliases: ["charleston port", "port charleston"] },
  { name: "Port de Norfolk, États-Unis", coordinates: [-76.2859, 36.8468], type: "port", aliases: ["norfolk port", "port norfolk"] },
  { name: "Port de Seattle, États-Unis", coordinates: [-122.3328, 47.6097], type: "port", aliases: ["seattle port", "port seattle"] },
  { name: "Port de Tacoma, États-Unis", coordinates: [-122.4594, 47.2529], type: "port", aliases: ["tacoma port", "port tacoma"] },
  { name: "Port de Miami, États-Unis", coordinates: [-80.1918, 25.7617], type: "port", aliases: ["miami port", "port miami"] },
  { name: "Port de Vancouver, Canada", coordinates: [-123.1207, 49.2827], type: "port", aliases: ["vancouver port", "port vancouver"] },
  { name: "Port de Montréal, Canada", coordinates: [-73.5673, 45.5017], type: "port", aliases: ["montreal port", "port montreal"] },
  { name: "Port de Halifax, Canada", coordinates: [-63.5729, 44.6488], type: "port", aliases: ["halifax port", "port halifax"] },
  { name: "Port de Santos, Brésil", coordinates: [-46.3322, -23.9618], type: "port", aliases: ["santos port", "port santos"] },
  { name: "Port de Rio de Janeiro, Brésil", coordinates: [-43.1729, -22.9068], type: "port", aliases: ["rio port", "port rio"] },
  { name: "Port de Buenos Aires, Argentine", coordinates: [-58.3816, -34.6037], type: "port", aliases: ["buenos aires port", "port buenos aires"] },
  { name: "Port de Valparaíso, Chili", coordinates: [-71.6270, -33.0472], type: "port", aliases: ["valparaiso port", "port valparaiso"] },
  { name: "Port de Callao, Pérou", coordinates: [-77.1181, -12.0567], type: "port", aliases: ["callao port", "port callao"] },
  { name: "Port de Cartagena, Colombie", coordinates: [-75.5518, 10.3910], type: "port", aliases: ["cartagena port", "port cartagena"] },
  { name: "Port de Veracruz, Mexique", coordinates: [-96.1342, 19.2006], type: "port", aliases: ["veracruz port", "port veracruz"] },
  { name: "Port de Manzanillo, Mexique", coordinates: [-104.3190, 19.1028], type: "port", aliases: ["manzanillo port", "port manzanillo"] },

  // Major Global Ports - Oceania
  { name: "Port de Sydney, Australie", coordinates: [151.2093, -33.8688], type: "port", aliases: ["sydney port", "port sydney", "port botany"] },
  { name: "Port de Melbourne, Australie", coordinates: [144.9631, -37.8136], type: "port", aliases: ["melbourne port", "port melbourne"] },
  { name: "Port de Brisbane, Australie", coordinates: [153.0260, -27.3818], type: "port", aliases: ["brisbane port", "port brisbane"] },
  { name: "Port de Fremantle, Australie", coordinates: [115.7454, -32.0569], type: "port", aliases: ["fremantle port", "port fremantle", "perth port"] },
  { name: "Port d'Auckland, Nouvelle-Zélande", coordinates: [174.7633, -36.8485], type: "port", aliases: ["auckland port", "port auckland"] },
  { name: "Port de Tauranga, Nouvelle-Zélande", coordinates: [176.1651, -37.6878], type: "port", aliases: ["tauranga port", "port tauranga"] },

  // Major International Airports - Africa
  { name: "Aéroport Jomo Kenyatta, Nairobi", coordinates: [36.9278, -1.3192], type: "airport", aliases: ["nairobi airport", "jomo kenyatta", "nbo", "airport nairobi"] },
  { name: "Aéroport O.R. Tambo, Johannesburg", coordinates: [28.2460, -26.1392], type: "airport", aliases: ["johannesburg airport", "or tambo", "jnb", "airport johannesburg"] },
  { name: "Aéroport du Cap", coordinates: [18.6017, -33.9648], type: "airport", aliases: ["cape town airport", "cpt", "airport cape town"] },
  { name: "Aéroport Mohammed V, Casablanca", coordinates: [-7.5895, 33.3675], type: "airport", aliases: ["casablanca airport", "cmn", "mohammed v", "airport casablanca"] },
  { name: "Aéroport du Caire", coordinates: [31.4056, 30.1219], type: "airport", aliases: ["cairo airport", "cai", "airport cairo"] },
  { name: "Aéroport de Lagos", coordinates: [3.3211, 6.5772], type: "airport", aliases: ["lagos airport", "los", "murtala mohammed", "airport lagos"] },
  { name: "Aéroport de Dakar", coordinates: [-17.0732, 14.7397], type: "airport", aliases: ["dakar airport", "dss", "leopold sedar senghor", "airport dakar"] },
  { name: "Aéroport d'Abidjan", coordinates: [-3.9263, 5.2614], type: "airport", aliases: ["abidjan airport", "abj", "felix houphouet boigny", "airport abidjan"] },
  { name: "Aéroport d'Addis-Abeba", coordinates: [38.7969, 9.0054], type: "airport", aliases: ["addis ababa airport", "add", "bole airport", "airport addis"] },
  { name: "Aéroport d'Alger", coordinates: [3.2154, 36.6910], type: "airport", aliases: ["algiers airport", "alg", "houari boumediene", "airport alger"] },
  { name: "Aéroport de Tunis", coordinates: [10.2272, 36.8510], type: "airport", aliases: ["tunis airport", "tun", "carthage airport", "airport tunis"] },
  { name: "Aéroport de Rabat", coordinates: [-6.7515, 34.0515], type: "airport", aliases: ["rabat airport", "rba", "sale airport", "airport rabat"] },
  { name: "Aéroport de Marrakech", coordinates: [-8.0363, 31.6069], type: "airport", aliases: ["marrakech airport", "rak", "menara airport", "airport marrakech"] },
  { name: "Aéroport de Accra", coordinates: [-0.1665, 5.6052], type: "airport", aliases: ["accra airport", "acc", "kotoka airport", "airport accra"] },
  { name: "Aéroport de Kigali", coordinates: [30.1395, -1.9686], type: "airport", aliases: ["kigali airport", "kgl", "airport kigali"] },
  { name: "Aéroport d'Entebbe", coordinates: [32.4435, 0.0424], type: "airport", aliases: ["entebbe airport", "ebb", "kampala airport", "airport entebbe"] },
  { name: "Aéroport de Dar es Salaam", coordinates: [39.2026, -6.8781], type: "airport", aliases: ["dar es salaam airport", "dar airport", "julius nyerere", "airport dar"] },
  { name: "Aéroport de Lusaka", coordinates: [28.4529, -15.3308], type: "airport", aliases: ["lusaka airport", "lun", "airport lusaka"] },
  { name: "Aéroport de Harare", coordinates: [31.0928, -17.9318], type: "airport", aliases: ["harare airport", "hre", "airport harare"] },
  { name: "Aéroport de Maputo", coordinates: [32.5729, -25.9208], type: "airport", aliases: ["maputo airport", "mpm", "airport maputo"] },

  // Major International Airports - Europe
  { name: "Aéroport Charles de Gaulle, Paris", coordinates: [2.5500, 49.0097], type: "airport", aliases: ["cdg", "charles de gaulle", "roissy", "airport paris", "aeroport paris"] },
  { name: "Aéroport d'Orly, Paris", coordinates: [2.3597, 48.7233], type: "airport", aliases: ["orly", "ory", "airport orly", "aeroport orly"] },
  { name: "Aéroport Heathrow, Londres", coordinates: [-0.4543, 51.4700], type: "airport", aliases: ["heathrow", "lhr", "airport london", "aeroport londres"] },
  { name: "Aéroport de Francfort, Allemagne", coordinates: [8.5706, 50.0379], type: "airport", aliases: ["frankfurt", "fra", "airport frankfurt", "aeroport francfort"] },
  { name: "Aéroport Schiphol, Amsterdam", coordinates: [4.7683, 52.3081], type: "airport", aliases: ["schiphol", "ams", "airport amsterdam", "aeroport amsterdam"] },
  { name: "Aéroport de Madrid, Espagne", coordinates: [-3.5676, 40.4719], type: "airport", aliases: ["madrid barajas", "mad", "airport madrid", "barajas"] },
  { name: "Aéroport de Rome Fiumicino", coordinates: [12.2389, 41.8003], type: "airport", aliases: ["fiumicino", "fco", "rome airport", "airport rome"] },
  { name: "Aéroport de Munich, Allemagne", coordinates: [11.7861, 48.3538], type: "airport", aliases: ["munich", "muc", "airport munich"] },
  { name: "Aéroport de Zurich, Suisse", coordinates: [8.5617, 47.4647], type: "airport", aliases: ["zurich", "zur", "airport zurich"] },
  { name: "Aéroport de Vienne, Autriche", coordinates: [16.5697, 48.1103], type: "airport", aliases: ["vienna", "vie", "airport vienna"] },
  { name: "Aéroport de Copenhague, Danemark", coordinates: [12.6561, 55.6180], type: "airport", aliases: ["copenhagen", "cph", "airport copenhagen"] },
  { name: "Aéroport d'Oslo, Norvège", coordinates: [11.1004, 60.1939], type: "airport", aliases: ["oslo", "osl", "gardermoen", "airport oslo"] },
  { name: "Aéroport de Stockholm, Suède", coordinates: [17.9186, 59.6519], type: "airport", aliases: ["stockholm", "arn", "arlanda", "airport stockholm"] },
  { name: "Aéroport d'Helsinki, Finlande", coordinates: [24.9633, 60.3172], type: "airport", aliases: ["helsinki", "hel", "vantaa", "airport helsinki"] },
  { name: "Aéroport de Dublin, Irlande", coordinates: [-6.2700, 53.4213], type: "airport", aliases: ["dublin", "dub", "airport dublin"] },
  { name: "Aéroport de Lisbonne, Portugal", coordinates: [-9.1354, 38.7813], type: "airport", aliases: ["lisbon", "lis", "airport lisbon"] },
  { name: "Aéroport d'Athènes, Grèce", coordinates: [23.9486, 37.9365], type: "airport", aliases: ["athens", "ath", "airport athens"] },
  { name: "Aéroport d'Istanbul, Turquie", coordinates: [28.8142, 41.2619], type: "airport", aliases: ["istanbul", "ist", "airport istanbul"] },
  { name: "Aéroport de Moscou Domodedovo", coordinates: [37.9063, 55.4087], type: "airport", aliases: ["moscow", "dme", "domodedovo", "airport moscow"] },

  // Major International Airports - Asia
  { name: "Aéroport Changi, Singapour", coordinates: [103.9915, 1.3644], type: "airport", aliases: ["changi", "sin", "airport singapore", "aeroport singapour"] },
  { name: "Aéroport Narita, Tokyo", coordinates: [140.3929, 35.7719], type: "airport", aliases: ["narita", "nrt", "airport tokyo", "aeroport tokyo"] },
  { name: "Aéroport de Haneda, Tokyo", coordinates: [139.7798, 35.5494], type: "airport", aliases: ["haneda", "hnd", "airport haneda"] },
  { name: "Aéroport International de Hong Kong", coordinates: [113.9158, 22.3080], type: "airport", aliases: ["hong kong", "hkg", "airport hong kong"] },
  { name: "Aéroport International de Pékin", coordinates: [116.5974, 40.0801], type: "airport", aliases: ["beijing", "pek", "capital airport", "airport beijing"] },
  { name: "Aéroport de Shanghai Pudong", coordinates: [121.8050, 31.1443], type: "airport", aliases: ["shanghai", "pvg", "pudong", "airport shanghai"] },
  { name: "Aéroport International de Dubaï", coordinates: [55.3644, 25.2532], type: "airport", aliases: ["dxb", "dubai airport", "airport dubai"] },
  { name: "Aéroport International de Doha", coordinates: [51.6081, 25.2731], type: "airport", aliases: ["doha", "doh", "hamad airport", "airport doha"] },
  { name: "Aéroport d'Abu Dhabi", coordinates: [54.6515, 24.4330], type: "airport", aliases: ["abu dhabi", "auh", "airport abu dhabi"] },
  { name: "Aéroport de Kuala Lumpur", coordinates: [101.7098, 2.7456], type: "airport", aliases: ["kuala lumpur", "kul", "klia", "airport kuala lumpur"] },
  { name: "Aéroport de Bangkok Suvarnabhumi", coordinates: [100.7501, 13.6900], type: "airport", aliases: ["bangkok", "bkk", "suvarnabhumi", "airport bangkok"] },
  { name: "Aéroport d'Incheon, Séoul", coordinates: [126.4407, 37.4691], type: "airport", aliases: ["seoul", "icn", "incheon", "airport seoul"] },
  { name: "Aéroport de Taipei Taoyuan", coordinates: [121.2325, 25.0797], type: "airport", aliases: ["taipei", "tpe", "taoyuan", "airport taipei"] },
  { name: "Aéroport de Mumbai", coordinates: [72.8679, 19.0896], type: "airport", aliases: ["mumbai", "bom", "bombay airport", "airport mumbai"] },
  { name: "Aéroport de Delhi", coordinates: [77.1025, 28.7041], type: "airport", aliases: ["delhi", "del", "new delhi", "airport delhi"] },
  { name: "Aéroport de Bengaluru", coordinates: [77.7081, 13.1986], type: "airport", aliases: ["bangalore", "blr", "bengaluru", "airport bangalore"] },
  { name: "Aéroport de Chennai", coordinates: [80.1693, 12.9941], type: "airport", aliases: ["chennai", "maa", "madras", "airport chennai"] },
  { name: "Aéroport de Hyderabad", coordinates: [78.4298, 17.2403], type: "airport", aliases: ["hyderabad", "hyd", "airport hyderabad"] },
  { name: "Aéroport de Colombo", coordinates: [79.8841, 7.1808], type: "airport", aliases: ["colombo", "cmb", "bandaranaike", "airport colombo"] },
  { name: "Aéroport de Dhaka", coordinates: [90.3978, 23.8103], type: "airport", aliases: ["dhaka", "dac", "hazrat shahjalal", "airport dhaka"] },
  { name: "Aéroport de Karachi", coordinates: [67.1608, 24.9065], type: "airport", aliases: ["karachi", "khi", "jinnah", "airport karachi"] },
  { name: "Aéroport d'Islamabad", coordinates: [72.8286, 33.5651], type: "airport", aliases: ["islamabad", "isb", "airport islamabad"] },
  { name: "Aéroport de Jakarta", coordinates: [106.6557, -6.1256], type: "airport", aliases: ["jakarta", "cgk", "soekarno hatta", "airport jakarta"] },
  { name: "Aéroport de Manille", coordinates: [121.0198, 14.5086], type: "airport", aliases: ["manila", "mnl", "ninoy aquino", "airport manila"] },
  { name: "Aéroport de Ho Chi Minh", coordinates: [106.6519, 10.8188], type: "airport", aliases: ["ho chi minh", "sgn", "tan son nhat", "airport saigon"] },

  // Major International Airports - North America
  { name: "Aéroport JFK, New York", coordinates: [-73.7781, 40.6413], type: "airport", aliases: ["jfk", "kennedy", "airport new york", "aeroport new york"] },
  { name: "Aéroport LAX, Los Angeles", coordinates: [-118.4085, 33.9425], type: "airport", aliases: ["lax", "airport los angeles", "aeroport los angeles"] },
  { name: "Aéroport O'Hare, Chicago", coordinates: [-87.9073, 41.9742], type: "airport", aliases: ["ohare", "ord", "chicago airport", "airport chicago"] },
  { name: "Aéroport de Miami", coordinates: [-80.2906, 25.7932], type: "airport", aliases: ["miami", "mia", "airport miami"] },
  { name: "Aéroport de San Francisco", coordinates: [-122.3748, 37.6213], type: "airport", aliases: ["san francisco", "sfo", "airport san francisco"] },
  { name: "Aéroport de Seattle", coordinates: [-122.3088, 47.4502], type: "airport", aliases: ["seattle", "sea", "tacoma", "airport seattle"] },
  { name: "Aéroport de Boston", coordinates: [-71.0096, 42.3656], type: "airport", aliases: ["boston", "bos", "logan", "airport boston"] },
  { name: "Aéroport de Las Vegas", coordinates: [-115.1523, 36.0840], type: "airport", aliases: ["las vegas", "las", "mccarran", "airport las vegas"] },
  { name: "Aéroport de Denver", coordinates: [-106.6890, 39.8561], type: "airport", aliases: ["denver", "den", "airport denver"] },
  { name: "Aéroport d'Atlanta", coordinates: [-84.4281, 33.6367], type: "airport", aliases: ["atlanta", "atl", "hartsfield", "airport atlanta"] },
  { name: "Aéroport de Toronto Pearson", coordinates: [-79.6248, 43.6777], type: "airport", aliases: ["toronto", "yyz", "pearson", "airport toronto"] },
  { name: "Aéroport de Vancouver", coordinates: [-123.1816, 49.1951], type: "airport", aliases: ["vancouver", "yvr", "airport vancouver"] },
  { name: "Aéroport de Montréal", coordinates: [-73.7413, 45.4706], type: "airport", aliases: ["montreal", "yul", "trudeau", "airport montreal"] },
  { name: "Aéroport de Mexico", coordinates: [-99.0720, 19.4363], type: "airport", aliases: ["mexico city", "mex", "benito juarez", "airport mexico"] },

  // Major International Airports - South America
  { name: "Aéroport de São Paulo Guarulhos", coordinates: [-46.4729, -23.4356], type: "airport", aliases: ["sao paulo", "gru", "guarulhos", "airport sao paulo"] },
  { name: "Aéroport de Rio de Janeiro", coordinates: [-43.2502, -22.8106], type: "airport", aliases: ["rio", "gig", "galeao", "airport rio"] },
  { name: "Aéroport de Buenos Aires", coordinates: [-58.5358, -34.8222], type: "airport", aliases: ["buenos aires", "eze", "ezeiza", "airport buenos aires"] },
  { name: "Aéroport de Lima", coordinates: [-77.1144, -12.0219], type: "airport", aliases: ["lima", "lim", "jorge chavez", "airport lima"] },
  { name: "Aéroport de Bogotá", coordinates: [-74.1469, 4.7016], type: "airport", aliases: ["bogota", "bog", "el dorado", "airport bogota"] },
  { name: "Aéroport de Santiago", coordinates: [-70.7856, -33.3928], type: "airport", aliases: ["santiago", "scl", "arturo merino", "airport santiago"] },
  { name: "Aéroport de Caracas", coordinates: [-66.9918, 10.6008], type: "airport", aliases: ["caracas", "ccs", "maiquetia", "airport caracas"] },
  { name: "Aéroport de Quito", coordinates: [-78.3578, -0.1292], type: "airport", aliases: ["quito", "uio", "mariscal sucre", "airport quito"] },
  { name: "Aéroport de La Paz", coordinates: [-68.1925, -16.5133], type: "airport", aliases: ["la paz", "lpb", "el alto", "airport la paz"] },

  // Major International Airports - Oceania
  { name: "Aéroport de Sydney", coordinates: [151.1772, -33.9399], type: "airport", aliases: ["sydney", "syd", "kingsford smith", "airport sydney"] },
  { name: "Aéroport de Melbourne", coordinates: [144.8432, -37.6690], type: "airport", aliases: ["melbourne", "mel", "tullamarine", "airport melbourne"] },
  { name: "Aéroport de Brisbane", coordinates: [153.1175, -27.3842], type: "airport", aliases: ["brisbane", "bne", "airport brisbane"] },
  { name: "Aéroport de Perth", coordinates: [115.9672, -31.9403], type: "airport", aliases: ["perth", "per", "airport perth"] },
  { name: "Aéroport d'Auckland", coordinates: [174.7850, -37.0082], type: "airport", aliases: ["auckland", "akl", "airport auckland"] },
  { name: "Aéroport de Christchurch", coordinates: [172.5320, -43.4865], type: "airport", aliases: ["christchurch", "chc", "airport christchurch"] },

  // Major Global Cities
  { name: "Paris, France", coordinates: [2.3522, 48.8566], type: "city", aliases: ["paris"] },
  { name: "Londres, Royaume-Uni", coordinates: [-0.1276, 51.5074], type: "city", aliases: ["london", "londres"] },
  { name: "New York, États-Unis", coordinates: [-74.0060, 40.7128], type: "city", aliases: ["new york", "nyc"] },
  { name: "Tokyo, Japon", coordinates: [139.6917, 35.6895], type: "city", aliases: ["tokyo"] },
  { name: "Shanghai, Chine", coordinates: [121.4737, 31.2304], type: "city", aliases: ["shanghai"] },
  { name: "Singapour", coordinates: [103.8198, 1.3521], type: "city", aliases: ["singapore"] },
  { name: "Dubaï, Émirats Arabes Unis", coordinates: [55.2708, 25.2048], type: "city", aliases: ["dubai"] },
  { name: "Sydney, Australie", coordinates: [151.2093, -33.8688], type: "city", aliases: ["sydney"] },
  { name: "Le Cap, Afrique du Sud", coordinates: [18.4241, -33.9249], type: "city", aliases: ["cape town", "le cap"] },
  { name: "São Paulo, Brésil", coordinates: [-46.6333, -23.5505], type: "city", aliases: ["sao paulo"] },
  { name: "Nairobi, Kenya", coordinates: [36.8219, -1.2921], type: "city", aliases: ["nairobi"] },
  { name: "Johannesburg, Afrique du Sud", coordinates: [28.0473, -26.2041], type: "city", aliases: ["johannesburg", "joburg"] },
  { name: "Casablanca, Maroc", coordinates: [-7.5898, 33.5731], type: "city", aliases: ["casablanca"] },
  { name: "Lagos, Nigéria", coordinates: [3.3792, 6.5244], type: "city", aliases: ["lagos"] },
  { name: "Dakar, Sénégal", coordinates: [-17.4441, 14.7167], type: "city", aliases: ["dakar"] },
  { name: "Abidjan, Côte d'Ivoire", coordinates: [-4.0435, 5.3599], type: "city", aliases: ["abidjan"] },
  { name: "Accra, Ghana", coordinates: [-0.1969, 5.6037], type: "city", aliases: ["accra"] },
  { name: "Kinshasa, République Démocratique du Congo", coordinates: [15.2663, -4.4419], type: "city", aliases: ["kinshasa"] },
  { name: "Durban, Afrique du Sud", coordinates: [31.0218, -29.8587], type: "city", aliases: ["durban"] }
];